### ISSUE TITLE
Error in the green waste query in Budaörs

### ISSUE THREAD

**Issue by hundavide** [amaximus/fkf-garbage-collection-card#10]
In the case of Budaörs, it queries the 3 types of waste with one single query, as far as I can see from the code, the problem may be that in the case of Budapest there are 2 separate requests 1. for municipal and selective and 2. for green waste. When the extension was written in winter there was no green waste, so this difference in the result didn't come up in the testing. Two result files are attached: the list from FKF (https://www.fkf.hu/hulladeknaptar-budaors) and the list queried by HA with the current code. For testing "Árvácska utca" was used.
![01](https://user-images.githubusercontent.com/111654226/224840789-a8067267-2e87-4c2f-ae9e-ad892276f397.png)
![02](https://user-images.githubusercontent.com/111654226/224840813-85a91406-3c24-4ec7-9bdb-d2fd93e9782a.png)

**Comment by amaximus** [comment]
This is not related to the card, but the custom integration.

I just pushed version 0.7.1 that fixes the green schedule for Budaörs.

Please update your custom component and get back to me with results.

**Comment by amaximus** [comment]
Please update your custom component and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by amaximus** [comment]
@hundavide  any update on this issue?

**Comment by hundavide** [comment]
Many thanks, works fine!
