### ISSUE TITLE
Appearance on two displays

### ISSUE THREAD

**Issue by bgeza** [amaximus/fkf-garbage-collection-card#11]
Hi Maximus,

I have two displays and for some reason the card appear differently on these:

![image](https://github.com/user-attachments/assets/af7a39be-c8cf-4855-b3ef-21bd1b9cc9ab)

and

![image](https://github.com/user-attachments/assets/bef56f78-baed-43d9-9181-5bc6262adf41)

Because of the space limit on the 2nd display, I updated en.json the days unit name as  "days": "d" to decrease the width, but strangely this abbreviation appear only on the 1st display.

Could you please advise?

Thanks

**Comment by amaximus** [comment]
Hi @bgeza , have you tried cleaning the browser cache and reloading the page (shift-F5)?

**Comment by bgeza** [comment]
crap... I cleared previously the companion cache, but this had no effect... now I cleared the Fully Kiosk cache, and it works.
Thanks for your prompt answer!
