### ISSUE TITLE
"days" localization

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection-card#2]
Angolul jelenik meg hogy "days":
![kép](https://user-images.githubusercontent.com/1550668/80955374-807bdf00-8dff-11ea-951f-ef400a5c3766.png)

Egyelőre kézzel javítom ki frissítés után `(${attribute.indays} nap)`

Köszönjük!

**Comment by amaximus** [comment]
Added fix for days localization in version 0.4.0.
Please update and get back to me with information.

**Comment by nagyrobi** [comment]
This is OK, thank you.
