### ISSUE TITLE
Items arrangement

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection-card#3]
Currently the items on the card are misaligned, compared to other standard lovelace cards:
![kép](https://user-images.githubusercontent.com/1550668/80955793-1f084000-8e00-11ea-83d8-83f5178fa638.png)

Suggestion:
![kép](https://user-images.githubusercontent.com/1550668/80955971-8e7e2f80-8e00-11ea-8ca7-b1a2f58b4943.png)
(+writing the first character uppercase)

**Comment by amaximus** [comment]
Added fix for alignement in version 0.4.0.
Please update and get back to me with information.

**Comment by nagyrobi** [comment]
Now it's like this:
![kép](https://user-images.githubusercontent.com/1550668/80969514-0016a780-8e1a-11ea-85a1-7bda2d0c3a15.png)

Still not in sync. 
To fix the trashcan icon, I have to change `padding-left: 8px;` to `padding-left: 20px;`, but I have no clue about the others...

**Comment by amaximus** [comment]
Pushed another update on alignement.

**Comment by nagyrobi** [comment]
It's getting better now, thank you:
![kép](https://user-images.githubusercontent.com/1550668/80975453-68698700-8e22-11ea-8df0-f55a5b6837be.png)

**Comment by amaximus** [comment]
Yet another release adjusting alignement.

**Comment by quieThu** [comment]
I also have a proposal for adjusting the card to fit better to the standard lovelace elements.

> 
      table {
        width: 99%;
        padding: 0px;
        border: none;
        padding-left: 21px;
      }
      th, td {
        padding: 10px;
      }
      .tdicon {
        width: 24px;
        padding: 0px;


**Left: Current
Right: Suggestion**
![padding](https://user-images.githubusercontent.com/60850998/81327456-93124480-909b-11ea-8ef4-1a282f85d55d.jpg)

**Comment by quieThu** [comment]
I've created a quick mocup that show my ideas for further developement, but please just take it as submission for more discussion. I know this would be a larger redesign, but maybe it provides inspiration for everyone. For a more cleaner look my idea is to show only one icon column, and use the text fields to display all the type of trash that'll be collected.
What do you think?

![layout_suggestion](https://user-images.githubusercontent.com/60850998/81330997-31ed6f80-90a1-11ea-9de5-e25fe9d9f420.jpg)

**Comment by amaximus** [comment]
@quieThu , thanks for the recommendations.
Added recommended alignement settings.
Added one_icon parameter to support displaying only one icon. Since this topic is about alignement, please open different issue for further enhancement ideas.
