### ISSUE TITLE
Layout revamp ideas

### ISSUE THREAD

**Issue by quieThu** [amaximus/fkf-garbage-collection-card#4]
I really like this card so far, thank you very much for it!

My suggestion is to rearrange the table columns to achieve a more streamlined look that could help digesting the information easier.

The column order could be:
|icon1| |icon2| |description| |date| |weekday| |numberofdays| 

**Left: Current
Right: Suggestion (with one_icon: true and w_day: false)**
![layout_redesign](https://user-images.githubusercontent.com/60850998/81419041-e80e9300-914d-11ea-8e0c-2a08762c109d.jpg)

**Comment by amaximus** [comment]
I'd prefer keeping the current layout with icons, date and day values on left and garbage type on right to comply with the general entity layout.

You can however fork this repo and do your desired changes in the forked repo.
