### ISSUE TITLE
Doesn't work outside HACS

### ISSUE THREAD

**Issue by DirtYiCE** [amaximus/fkf-garbage-collection-card#8]
The card can't load the translations when installed manually, since it expects a hacs path:
https://github.com/amaximus/fkf-garbage-collection-card/blob/292d58760eae6b1097de8054de7cb21aaced7e5f/dist/fkf-garbage-collection-card.js#L8-L9
From what can I see in the code, it has some support for the cases when it fails to load the translation, but `translationJSONobj` is initialized to `"undefined"` (a string),  which means the if here won't catch it:
https://github.com/amaximus/fkf-garbage-collection-card/blob/292d58760eae6b1097de8054de7cb21aaced7e5f/dist/fkf-garbage-collection-card.js#L96
(its type will be `string`, not `undefined`), and then fail when it tries to index the string. `translationJSONobj` should be initialized to `undefined`, but I have no idea how can you get the path to your js file (if it's possible at all).

**Comment by amaximus** [comment]
Recently release (0.9.0) fixes this issue.

Please update the card and its configuration and get back to me with results.

**Comment by DirtYiCE** [comment]
It works now if I set `install_path` correctly, thanks.
