### ISSUE TITLE
Extension for Budaörs

### ISSUE THREAD

**Issue by hundavide** [amaximus/fkf-garbage-collection-card#9]
Dear Author,

Could you please extrend your program to process the garbage collection schedule in Budaörs, please? 
It works similar like FKF at Budapest, couple differences noticed:

1. URL is different: https://www.fkf.hu/hulladeknaptar-budaors
2. There is only one parameter in request  (street name, like: Alma utca)
3. Here all the three types of waste (communal, selective and green) is included in the given resoult for the next 1 month.

Many thanks in advance!
hundavide

**Comment by amaximus** [comment]
This should have been opened at the integration https://github.com/amaximus/fkf-garbage-collection, not the frontend component.

Anyway, recently pushed version (0.6.0) of the integration adds support for Budaörs.

Please update the integration, configure the sensor for Budaörs and get back to me with results.
